// examples/react-example.tsx
/**
 * React Integration Example
 * 
 * This example shows how to use secure-fetch-client in a React application:
 * - Using with useEffect
 * - Integrating with SWR
 * - Creating a custom hook
 * - Error handling in components
 */

import { useEffect, useState } from "react";
import { ApiClient } from "secure-fetch-client";

// Create a shared client instance
const apiClient = new ApiClient({
  baseUrl: "https://api.example.com",
});

// Example 1: Basic usage with useEffect
interface User {
  id: string;
  name: string;
  email: string;
}

function UserProfile({ userId }: { userId: string }) {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function fetchUser() {
      try {
        setLoading(true);
        const response = await apiClient.request<User>({
          url: `/users/${userId}`,
          method: "GET",
        });

        if (!cancelled) {
          if (response.ok) {
            setUser(response.data);
            setError(null);
          } else {
            setError(response.error.message);
          }
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError("Failed to fetch user");
          setLoading(false);
        }
      }
    }

    fetchUser();

    return () => {
      cancelled = true;
    };
  }, [userId]);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error}</div>;
  if (!user) return null;

  return (
    <div>
      <h1>{user.name}</h1>
      <p>{user.email}</p>
    </div>
  );
}

// Example 2: Custom hook for API calls
function useApi<T>(url: string, options?: { method?: string; body?: unknown }) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function fetchData() {
      try {
        setLoading(true);
        const response = await apiClient.request<T>({
          url,
          method: (options?.method as any) || "GET",
          body: options?.body,
        });

        if (!cancelled) {
          if (response.ok) {
            setData(response.data);
            setError(null);
          } else {
            setError(response.error.message);
          }
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError("Request failed");
          setLoading(false);
        }
      }
    }

    fetchData();

    return () => {
      cancelled = true;
    };
  }, [url, JSON.stringify(options)]);

  return { data, loading, error };
}

// Usage of custom hook
function UsersList() {
  const { data: users, loading, error } = useApi<{ users: User[] }>("/users");

  if (loading) return <div>Loading users...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <ul>
      {users?.users.map((user) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}

// Example 3: Integration with SWR
import useSWR from "swr";

const swrFetcher = (url: string) =>
  apiClient
    .request({ url, method: "GET" })
    .then((res) => {
      if (!res.ok) throw new Error(res.error.message);
      return res.data;
    });

function UsersListWithSWR() {
  const { data, error, isLoading } = useSWR("/users", swrFetcher);

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <ul>
      {data?.users?.map((user: User) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}

// Example 4: Form submission
function CreateUserForm() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    const response = await apiClient.request<{ id: string }>({
      url: "/users",
      method: "POST",
      body: { name, email },
    });

    if (response.ok) {
      console.log("User created:", response.data.id);
      setName("");
      setEmail("");
    } else {
      setError(response.error.message);
    }

    setSubmitting(false);
  };

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Name"
      />
      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Email"
      />
      {error && <div style={{ color: "red" }}>{error}</div>}
      <button type="submit" disabled={submitting}>
        {submitting ? "Creating..." : "Create User"}
      </button>
    </form>
  );
}

export { UserProfile, useApi, UsersList, UsersListWithSWR, CreateUserForm };

// examples/angular-example.ts
/**
 * Angular Integration Example
 * 
 * This example shows how to use secure-fetch-client in an Angular application:
 * - Creating an injectable service
 * - Using with HttpClient
 * - Error handling with RxJS
 * - Dependency injection
 */

import { Injectable } from "@angular/core";
import { Observable, from, map, catchError, throwError } from "rxjs";
import { ApiClient } from "secure-fetch-client";
import type { ApiResponse } from "secure-fetch-client";

@Injectable({
  providedIn: "root",
})
export class ApiService {
  private client: ApiClient;

  constructor() {
    this.client = new ApiClient({
      baseUrl: "/api",
      defaultHeaders: {
        "x-client": "angular-app",
      },
    });
  }

  // Example 1: Basic service method
  getUsers(): Observable<ApiResponse<{ users: User[] }>> {
    return from(
      this.client.request<{ users: User[] }>({
        url: "/users",
        method: "GET",
      }),
    );
  }

  // Example 2: Service method with error handling
  getUser(id: string): Observable<User> {
    return from(
      this.client.request<User>({
        url: `/users/${id}`,
        method: "GET",
      }),
    ).pipe(
      map((response) => {
        if (response.ok) {
          return response.data;
        }
        throw new Error(response.error.message);
      }),
      catchError((error) => {
        console.error("API Error:", error);
        return throwError(() => error);
      }),
    );
  }

  // Example 3: Create user
  createUser(user: { name: string; email: string }): Observable<{ id: string }> {
    return from(
      this.client.request<{ id: string }>({
        url: "/users",
        method: "POST",
        body: user,
      }),
    ).pipe(
      map((response) => {
        if (response.ok) {
          return response.data;
        }
        throw new Error(response.error.message);
      }),
    );
  }

  // Example 4: Update user
  updateUser(id: string, updates: Partial<User>): Observable<User> {
    return from(
      this.client.request<User>({
        url: `/users/${id}`,
        method: "PUT",
        body: updates,
      }),
    ).pipe(
      map((response) => {
        if (response.ok) {
          return response.data;
        }
        throw new Error(response.error.message);
      }),
    );
  }

  // Example 5: Delete user
  deleteUser(id: string): Observable<void> {
    return from(
      this.client.request({
        url: `/users/${id}`,
        method: "DELETE",
      }),
    ).pipe(
      map((response) => {
        if (!response.ok) {
          throw new Error(response.error.message);
        }
      }),
    );
  }

  // Example 6: Set authentication tokens
  setAuthTokens(accessToken: string, refreshToken?: string): Promise<void> {
    return this.client.setTokens({ accessToken, refreshToken });
  }

  // Example 7: Clear tokens
  clearAuthTokens(): Promise<void> {
    return this.client.clearTokens();
  }
}

// Component usage example
import { Component, OnInit } from "@angular/core";

interface User {
  id: string;
  name: string;
  email: string;
}

@Component({
  selector: "app-users",
  template: `
    <div *ngIf="loading">Loading...</div>
    <div *ngIf="error">{{ error }}</div>
    <ul *ngIf="users">
      <li *ngFor="let user of users">{{ user.name }} - {{ user.email }}</li>
    </ul>
  `,
})
export class UsersComponent implements OnInit {
  users: User[] | null = null;
  loading = false;
  error: string | null = null;

  constructor(private apiService: ApiService) {}

  ngOnInit() {
    this.loadUsers();
  }

  loadUsers() {
    this.loading = true;
    this.error = null;

    this.apiService.getUsers().subscribe({
      next: (response) => {
        if (response.ok) {
          this.users = response.data.users;
        } else {
          this.error = response.error.message;
        }
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message;
        this.loading = false;
      },
    });
  }
}

// Example with async/await in component
@Component({
  selector: "app-user-profile",
  template: `
    <div *ngIf="user">
      <h1>{{ user.name }}</h1>
      <p>{{ user.email }}</p>
    </div>
  `,
})
export class UserProfileComponent implements OnInit {
  user: User | null = null;

  constructor(private apiService: ApiService) {}

  async ngOnInit() {
    try {
      this.user = await firstValueFrom(this.apiService.getUser("123"));
    } catch (error) {
      console.error("Failed to load user:", error);
    }
  }
}

import { firstValueFrom } from "rxjs";

export { ApiService, UsersComponent, UserProfileComponent };
